name: nsgt-torch

channels:
  - default
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - numba
  - scipy
  - conda-forge::cudatoolkit=11.3
  - conda-forge::cudnn=8.2.0
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - tqdm
  - libsndfile
  - ffmpeg
  - pip
  - pip:
    - musdb==0.3.1
    - museval==0.3.1
    - cupy-cuda113
    - seaborn
    - pandas
    - gitpython
    - matplotlib
    - line_profiler
    - tensorboard
    - memory_profiler
    - pytest
    - librosa>=0.9
    - torchinfo
    - "--editable=git+git://github.com/csteinmetz1/auraloss@main#egg=auraloss"
    - "--editable=git+git://github.com/OnAir-Music/onair-py#egg=onair"
    - "-e ."
